export const learningEn: Record<string, string> = {
  // Report Dialog
  'Báo lỗi nội dung': 'Report content issue',
  'Đóng': 'Close',
  'Đã gửi báo cáo thành công!': 'Report submitted successfully!',
  'Cảm ơn bạn đã đóng góp giúp cải thiện chất lượng bài học.': 'Thank you for helping improve lesson quality.',
  'Nếu phát hiện lỗi phiên âm, phát âm TTS không chuẩn, đáp án không chính xác hoặc câu hỏi khó hiểu, vui lòng gửi phản hồi cho ban biên tập.':
    'If you notice phonetic errors, inaccurate TTS pronunciation, wrong answers, or unclear questions, please submit feedback to the editorial team.',
  'Phiên bản nội dung:': 'Content version:',
  'Mã câu hỏi:': 'Question ID:',
  'Mã quy tắc:': 'Rule ID:',
  'Mô tả chi tiết lỗi': 'Detailed issue description',
  "Ví dụ: Chùm ký tự 'ea' trong từ steak bị xếp sai âm vị, âm mẫu đọc không chuẩn...":
    "e.g. The 'ea' cluster in 'steak' is assigned the wrong phoneme, sample audio is inaccurate...",
  'Hủy bỏ': 'Cancel',
  'Gửi báo cáo': 'Submit report',
  'Vui lòng nhập mô tả lỗi.': 'Please enter an issue description.',

  // Spelling Exercise
  'Từ mục tiêu:': 'Target word:',
  'Khu vực ghép từ ({{count}} mảnh đã chọn):': 'Word assembly area ({{count}} tiles selected):',
  'Hoàn tác': 'Undo',
  'Xóa hết': 'Clear all',
  'Khu vực các chữ cái đã ghép': 'Assembled letters area',
  'Chạm vào các mảnh ghép bên dưới theo đúng thứ tự để tạo thành từ':
    'Tap the tiles below in correct sequence to form the word',
  'Xóa mảnh ghép {{label}}': 'Remove tile {{label}}',
  'Kho mảnh ghép (chọn lần lượt):': 'Tile bank (select in order):',
  'Kho các mảnh ghép sẵn có': 'Available tile bank',
  'Chọn mảnh ghép {{label}}': 'Select tile {{label}}',

  // Speaking Exercise
  'Giọng {{accent}}': '{{accent}} accent',
  'Nghe âm mẫu': 'Play sample audio',
  '* Phát âm mẫu tạo bởi TTS trình duyệt (không phải audio kiểm duyệt chính thức).':
    '* Sample audio generated by browser TTS (not official verified audio).',
  'Luyện phát âm cùng Microphone': 'Practice pronunciation with microphone',
  'Nhấn nút để bắt đầu thu âm phát âm của bạn. Không chấm điểm giả lập AI.':
    'Press the button to start recording your pronunciation. No fake AI scores.',
  'Đã lưu bản thu âm thành công!': 'Recording saved successfully!',
  'Bản ghi âm thực tế của bạn đã được lưu trữ vào hệ thống.':
    'Your actual audio recording has been saved to the system.',
  'Dừng thu âm': 'Stop recording',
  'Đang ghi âm... Nhấn nút vuông để dừng': 'Recording... Press the square button to stop',
  'Tạm dừng': 'Pause',
  'Nghe lại bản thu': 'Listen to recording',
  'Thu lại': 'Re-record',
  'Lưu bản thu': 'Save recording',
  'Bắt đầu thu âm': 'Start recording',
  'Đang kết nối microphone...': 'Connecting to microphone...',
  'Nhấn mic để bắt đầu nói': 'Press mic to start speaking',
  'Bỏ qua bước nói': 'Skip speaking step',

  // Session Summary
  'Hoàn thành xuất sắc': 'Completed successfully',
  'Phiên ôn tập củng cố lỗi sai': 'Review session for missed questions',
  'Bài học lộ trình ngữ âm chuẩn': 'Core phonics path lesson',
  'Đúng {{correct}}/{{total}} câu': '{{correct}}/{{total}} questions correct',
  'Độ chính xác {{accuracy}}%': '{{accuracy}}% accuracy',
  'Luyện nói: {{status}}': 'Speaking: {{status}}',
  'Đã thu âm': 'Recorded',
  'Đã bỏ qua': 'Skipped',
  'Chưa thu âm': 'Not recorded',
  'Chi tiết các câu hỏi trong phiên': 'Question breakdown for this session',
  'Tổng cộng {{count}} câu': 'Total of {{count}} questions',
  'Từ "{{word}}"': 'Word "{{word}}"',
  'Chính xác': 'Correct',
  'Cần ôn lại': 'Needs review',
  'Chưa trả lời': 'Unanswered',
  'Quay lại lộ trình': 'Back to learning path',

  // Learning Session
  'Đang tải phiên học...': 'Loading learning session...',
  'Chuẩn bị các câu hỏi ngữ âm phản xạ': 'Preparing reflex phonics questions',
  'Không thể tải bài học': 'Unable to load lesson',
  'Không tìm thấy dữ liệu phiên học.': 'Learning session data not found.',
  'Thoát ra': 'Exit',
  'Thử lại': 'Retry',
  'Thoát bài học': 'Exit lesson',
  'Thoát phiên học': 'Exit learning session',
  'Bước luyện nói': 'Speaking step',
  'Tiến độ: {{answered}}/{{total}} câu': 'Progress: {{answered}}/{{total}} questions',
  'Ôn tập phản xạ': 'Reflex review',
  'Nhận diện nghĩa từ': 'Word meaning recognition',
  'Bóc tách & Ghép chữ': 'Segment & spell words',
  'Phản xạ âm ⇄ chữ': 'Sound ⇄ spelling reflex',
  'Nhiều đáp án đúng': 'Multiple correct answers',
  'Chọn đáp án chính xác:': 'Select the correct answer:',
  'Câu hỏi này có thể có một hoặc nhiều phương án chính xác. Hãy chọn tất cả phương án thỏa mãn.':
    'This question may have one or more correct choices. Please select all that apply.',
  'Chọn nghĩa tiếng Việt chính xác nhất cho từ vựng này.':
    'Select the most accurate Vietnamese meaning for this vocabulary word.',
  'Chạm các mảnh ghép chữ cái hoặc chùm âm vị để tạo thành từ hoàn chỉnh.':
    'Tap the letter or phoneme tiles to form the complete word.',
  'Hãy nhận diện quan hệ âm – chữ phù hợp với ngữ cảnh.':
    'Identify the sound-spelling correspondence matching this context.',
  'Minh họa từ vựng': 'Vocabulary illustration',
  'Ký hiệu âm vị:': 'Phonetic notation:',
  '* Âm mẫu TTS trình duyệt': '* Browser TTS sample audio',
  'Các phương án trả lời': 'Answer choices',
  'Chính xác xuất sắc!': 'Excellent! Correct!',
  'Chưa chính xác!': 'Not quite right!',
  'Tiếp tục': 'Continue',
  'Bạn đã nhận diện chuẩn xác quan hệ âm và chữ.': 'You accurately identified the sound-spelling relationship.',
  'Hãy ghi nhớ quy tắc này để phản xạ chính xác hơn.': 'Remember this rule to build faster phonics reflexes.',
  'Mẹo Phản Xạ Quy Tắc': 'Reflex Rule Tip',
  'Trong tiếng Anh, một tổ hợp chữ có thể chuyển hóa thành nhiều âm vị tùy thuộc vào trọng âm và ngữ cảnh từ.':
    'In English, a spelling pattern can represent multiple phonemes depending on stress and word context.',
  'Chuẩn giọng:': 'Target accent:',
  'Anh - Anh (UK)': 'British English (UK)',
  'Anh - Mỹ (US)': 'American English (US)',
  'Trạng thái:': 'Status:',
  'Nội dung đã kiểm duyệt': 'Verified content',
  'Danh sách câu hỏi': 'Questions list',
  '{{answered}}/{{total}} đã làm': '{{answered}}/{{total}} answered',
  'Chuyển đến câu hỏi {{number}}': 'Go to question {{number}}',
  'Báo lỗi câu hỏi này': 'Report this question',
  'Kiểm tra': 'Check',

  // Recorder Hook & Errors
  'Trình duyệt của bạn không hỗ trợ ghi âm microphone.': 'Your browser does not support microphone recording.',
  'Quyền truy cập microphone bị từ chối. Vui lòng cho phép quyền microphone trên trình duyệt hoặc chọn Bỏ qua.':
    'Microphone access was denied. Please allow microphone permission in your browser or choose Skip.',
  'Không thể kết nối với microphone thiết bị.': 'Could not connect to device microphone.',
  'Chưa có bản thu âm để lưu.': 'No recording available to save.',
  'Lỗi khi tải bản thu lên máy chủ.': 'Error uploading recording to server.',
  'Lỗi khi kiểm tra đáp án.': 'Error checking answer.',
  'Không thể bỏ qua bước nói.': 'Could not skip speaking step.',
};
